run_name: calibrated_inference_micro_${summary_net.arch}
experiment: InferenceExperiment

generative_model: CalibratedNPE

calibration_num_samples: 32
calibration_weight: 1.
conservative: True

defaults:
  - inference_micro
  - _self_