run_name: inference_${summary_net.arch}
experiment: InferenceExperiment

summary_dim: 96
target_indices: [0,1,2,3,4,5]

num_test_points: 750
num_posterior_samples: 5000
sample_batch_size: 750

generative_model: NPE
net:
  cond_dim: ${summary_dim}

data:
  file_by_file: True

training:
  epochs: 1000
  lr: 0.0001
  batch_size: 32
  test_batch_size: ${num_test_points}
  optimizer:
    name: AdamW

use_extra_summary_mlp: False
extra_mlp:
  units:
    - ${summary_dim}
    - ${summary_dim}
    - ${summary_dim}
  act: relu
  out_act: null
  drop: 0.

use_attn_pool: False
attn_pool:
  embed_dim: ${summary_dim}
  out_channels: ${summary_dim}

defaults:
  - default
  - preprocessing: xandy
  - net: inn
  - net@summary_net: vit
  - net@attn_pool: attn_head
  - _self_