run_name: summarized_regression_${net.arch}
experiment: RegressionExperiment

summary_net:
  backbone_dir: ???
latent_dim: 360

training:
  lr: 5.e-4
  epochs: 1000
  patience: 100

data:
  summarize: True
  file_by_file: True

net:
  units:
  - ${latent_dim}
  - ${latent_dim}
  - 6
  out_act: sigmoid
  
defaults:
  - regression
  - override net: mlp
  - net@summary_net: pretrained_vit
  - _self_