run_name: fine_regression_micro_${net.arch}
experiment: RegressionExperiment

summary_net:
  backbone_dir: ???
latent_dim: 360

training:
  lr: 5.e-4

data:
  summarize: True
  file_by_file: True

net:
  units:
  - ${latent_dim}
  - ${latent_dim}
  - 6
  out_act: sigmoid
  
defaults:
  - summarized_regression
  - override net@summary_net: pretrained_vit
  - override net: mlp
  - _self_